condition2.plot()
# plt.xlabel("Iteration")
# plt.ylabel("Network Latency")
# condition3.plot()
# plt.xlabel("Iteration")
# plt.ylabel("Network Latency")
# condition4.plot()
# plt.xlabel("Iteration")
# plt.ylabel("Network Latency")